name: Concurrency Demo

on:
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          echo "::group::The repository ${{ github.repository }} contains the following files"
          tree
          echo "::endgroup::"

      - name: Simulate work
        run: sleep 30  

  job_two:
    runs-on: ubuntu-latest
    steps:
      - name: Print job two start
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: Simulate work
        run: sleep 30
